title: Girish Shirasat
description: Personal Nerdy Muses
email: ""

remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

header_pages:
  - index.md
  - blogs.md

cv_url: "https://your-cv-link-here"  # Replace with your actual CV URL

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:year/:month/:day/:title/
