title: Girish Shirasat
description: Senior Director & Global Head – Automotive/Robotics System Software Architecture
email: girish.shirasat@gmail.com

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:year/:month/:day/:title/

linkedin_url: "https://www.linkedin.com/in/girish-shirasat"
github_url: "https://github.com/gizthenerd"
cv_url: "https://your-cv-link-here"
